name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Show available simulators
      run: xcrun simctl list devicetypes

    - name: Build
      run: |
        xcodebuild -project APPFORGE_V5.xcodeproj \
                   -scheme APPFORGE_V5 \
                   -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
                   clean build \
                   CODE_SIGNING_ALLOWED=NO

    - name: Build for iPad
      run: |
        xcodebuild -project APPFORGE_V5.xcodeproj \
                   -scheme APPFORGE_V5 \
                   -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation),OS=17.5' \
                   clean build \
                   CODE_SIGNING_ALLOWED=NO

    - name: Run Tests (if any)
      run: |
        xcodebuild -project APPFORGE_V5.xcodeproj \
                   -scheme APPFORGE_V5 \
                   -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
                   test \
                   CODE_SIGNING_ALLOWED=NO
      continue-on-error: true 